//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İnternetProgramcılıgıApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.secilenProjeler = new HashSet<secilenProjeler>();
        }
    
        public string ogrId { get; set; }
        public string ogrNo { get; set; }
        public string ogrAdSoyad { get; set; }
        public string ogrBolumId { get; set; }
        public string ogrBolumAd { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<secilenProjeler> secilenProjeler { get; set; }
    }
}
