//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İnternetProgramcılıgıApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class secilenProjeler
    {
        public string secProjeId { get; set; }
        public string secProjeOgrId { get; set; }
        public string secProjeDersId { get; set; }
        public string secProjeKonuId { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Konular Konular { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
